import type { Ring } from "@/lib/map-geometry";

/**
 * The outline of one wine appellation.
 *
 * Generated by scripts/build-region-shapes.py from the EU's own register and
 * the Eurac Research boundary map, one module per country under lib/regions.
 * Server-side only, and loaded one country at a time: all of them together are
 * a megabyte, and nobody has ever wanted to look at all of them together.
 */
export type RegionShape = {
  /**
   * The name flattened for matching — the same key EU_WINE_REGIONS uses, so a
   * bottle placed by the register lands on the shape of the place it names.
   */
  key: string;
  /** As the register spells it, alternatives and all: "Priorat / Priorato". */
  name: string;
  /** Exterior rings, largest first, in longitude and latitude. */
  rings: Ring[];
};

/**
 * Every appellation in one country, or nothing for a country the EU register
 * doesn't cover — Argentina, Australia, Chile, South Africa, the United States.
 *
 * A dynamic import so that opening Italy doesn't send France: these are big
 * data modules, and a static import of all twenty-one would put the lot in
 * every server bundle that touches the map.
 */
export async function shapesFor(iso: string): Promise<RegionShape[]> {
  try {
    const loaded = (await import(`@/lib/regions/${iso.toLowerCase()}`)) as {
      default: RegionShape[];
    };
    return loaded.default;
  } catch {
    return [];
  }
}
