const { boot, shot } = require('./lib');
const PHOTO='/tmp/claude-0/-home-user-wine-tracker/51ac2fc6-2848-5945-9ad7-a1982f33d24f/scratchpad/study/bottle-photo.jpg';
(async()=>{
  const {browser,page} = await boot();
  await page.goto('http://localhost:3210/add'); await page.waitForTimeout(2000);
  await page.locator('input[type=file]').setInputFiles(PHOTO);
  await page.waitForTimeout(4000);
  const f = n => page.locator(`input[name="${n}"]`);
  await page.getByPlaceholder('Producer').fill('Tenuta San Guido');
  await page.getByPlaceholder('What is it?').fill('Chianti Classico');
  await page.getByText('Loved it').click();
  await f('vintage').fill('2020');
  await page.locator('select').first().selectOption({label:'Red'});
  await f('grapes').fill('Sangiovese');
  await f('region').fill('Toscana');
  await f('country').fill('Italy');
  await f('price').fill('38');
  await page.waitForTimeout(500);
  await page.locator('textarea').fill('Decant 45 min. Drink 2026-2032. Bought at Berry Bros, en primeur. Drunk with bistecca.');
  await page.waitForTimeout(500);
  await page.screenshot({path:'/home/user/wine-tracker/.study-marg/18-add-filled.png', fullPage:true});
  console.log('FIELDS NOW:', await page.evaluate(()=>[...document.querySelectorAll('input,textarea,select')].map(e=>(e.name||e.type)+'='+JSON.stringify((e.value||'').slice(0,60))).join(' | ')));
  await page.getByText('ADD TO THE LOG').click();
  await page.waitForTimeout(4000);
  console.log('AFTER SAVE URL:', page.url());
  await page.screenshot({path:'/home/user/wine-tracker/.study-marg/19-added-detail.png', fullPage:true});
  console.log(await page.locator('body').innerText());
  await browser.close();
})();
