const { open, shot } = require('./helper.js');
(async () => {
  const { browser, ctx, page, errs } = await open();
  await page.goto('http://localhost:3210/add'); await page.waitForTimeout(1500);
  await page.setInputFiles('input[type=file]','/tmp/claude-0/-home-user-wine-tracker/51ac2fc6-2848-5945-9ad7-a1982f33d24f/scratchpad/study/bottle-photo.jpg');
  await page.waitForTimeout(4000);
  const sids = await page.evaluate(()=>[...document.querySelectorAll('select')].map(x=>({id:x.id,opts:[...x.options].map(o=>o.value)})));
  console.log('SELECTS', JSON.stringify(sids));
  await page.fill('#producer','Tenuta San Guido');
  await page.fill('#name','Chianti Classico');
  await page.getByText('Loved it', {exact:true}).click();
  await page.fill('#vintage','2020');
  await page.selectOption('#'+sids[0].id, sids[0].opts.find(o=>/red/i.test(o)) || sids[0].opts[1]);
  await page.fill('#grapes','Sangiovese');
  await page.fill('#region','Tuscany');
  await page.fill('#country','Italy');
  await page.fill('#price','11');
  await page.getByText('Fruity',{exact:true}).click();
  await page.getByText('Would buy again',{exact:true}).click();
  await page.fill('#notes','Nice easy red, would get again from Tesco.');
  await page.waitForTimeout(500);
  await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight)); await page.waitForTimeout(400);
  await shot(page,'35-form-filled-bottom');
  console.log('footer:', await page.evaluate(()=>document.body.innerText.split('\n').filter(Boolean).slice(-3).join(' | ')));
  await page.getByText('ADD TO THE LOG').click();
  await page.waitForTimeout(4500);
  console.log('URL after save', page.url());
  await shot(page,'36-after-save');
  console.log((await page.evaluate(()=>document.body.innerText)).replace(/\n+/g,' | ').slice(0,700));
  console.log('ERRS', JSON.stringify(errs.slice(0,8)));
  await browser.close();
})();
